import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col">
          <div className="navbar bg-base-300">
            <div className="flex-1">
              <a className="btn btn-ghost normal-case text-xl">NextJS</a>
            </div>
            <div className="flex-none">
              <ul className="menu menu-horizontal px-1">
                <li>
                  <Link href={'/'}>Home</Link>
                </li>
                <li>
                  <Link href={'/about'}>About</Link>
                </li>
                <li>
                  <details>
                    <summary>
                      Parent
                    </summary>
                    <ul className="p-2 bg-base-100">
                    </ul>
                  </details>
                </li>
              </ul>
            </div>
          </div>
          
          <div className='flex-1 m-5'>
            {children}
          </div>
          
          <footer className="footer footer-center p-4 bg-base-300 text-base-content">
            <aside>
              <p>Copyright © 2023 - All right reserved by ACME Industries Ltd</p>
            </aside>
          </footer>
        </main>
      </body>
    </html>
  )
}
